# Generated by Django 4.1.1 on 2022-10-22 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('Gender', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('demo_link', models.CharField(max_length=200, null=True)),
                ('source_link', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
