# Generated by Django 4.1.1 on 2022-10-23 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personDiscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hairColor', models.CharField(max_length=200)),
                ('Behavior', models.CharField(choices=[('Good', 'Up Vote'), ('Bad', 'Down Vote')], max_length=200)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource.username')),
            ],
        ),
        migrations.CreateModel(
            name='jobDiscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ManyToManyField(blank=True, to='resource.persondiscription')),
            ],
        ),
    ]
